#!/bin/bash

## changed for PRex Optimization
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    echo "./myTree2AscII [path contains the cut files]  "
    echo "example: ./myTree2AscII ../Result "
    exit
fi

ARCH=$(arch)
PROG=./tree2ascii
ROOTFILEDIR="/home/newdriver/Storage/Research/CRex_Experiment/optReplay/Result"

prefix="prexLHRS"
# Path that contains the cut 
DIR=$1
nfoil=1

des="Sieve.Full.test"

#IdOffSet=49
if [ -f $DIR/${des} ]
then
  mv -f $DIR/${des}  $DIR/${des}.old
fi



Id=0
# run 21646, -2% dp scan
keyrun=2566
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexLHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexLHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexLHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexLHRS_${keyrun}_-1.root  
        #\
        #$ROOTFILEDIR/prexLHRS_20826_-1_2.root 

        
Id=98
#21641 -1% dp scan
keyrun=2565    
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexLHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexLHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexLHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexLHRS_${keyrun}_-1.root 
        #\
        #$ROOTFILEDIR/prexLHRS_20827_-1_2.root \
        #$ROOTFILEDIR/prexLHRS_20827_-1_3.root 

Id=196
#21636 +1% dp scan
keyrun=2556    
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexLHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexLHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexLHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexLHRS_${keyrun}_-1.root 
     
     

Id=294
#21636 +1% dp scan
keyrun=2550    
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexLHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexLHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexLHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexLHRS_${keyrun}_-1.root
         


cat $DIR/Sieve._2566_p4.f51   $DIR/Sieve._2565_p4.f51 $DIR/Sieve._2556_p4.f51 $DIR/Sieve._2550_p4.f51 > $DIR/${des}
echo "Done!"
