#!/bin/bash

## changed for PRex Dp Optimization
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    echo "Usage for Dp ASCII data generater bash"
    echo "./myTree2AscII [path contains the cut files]  "
    echo "example: ./myTree2AscII ../Result \n"
    echo "The optfolder which is point to the path contains the root file is hardcoded. you may need to change that"
    exit
fi

ARCH=$(arch)
PROG=./tree2ascii
ROOTFILEDIR="/home/newdriver/Storage/Research/CRex_Experiment/optReplay/Result" 

prefix="prexRHRS"
# Path that contains the cut 
DIR=$1
nfoil=1

des="Dp.Full.test"

#IdOffSet=49
if [ -f $DIR/${des} ]
then
  mv -f $DIR/${des}  $DIR/${des}.old
fi

echo "************************************************************"

Id=0
# run 21642, -2% dp scan
keyrun=20826
$PROG -pv -d DpVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Dp._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_2.root 

#cat  $DIR/Sieve._20826_p4.f51 > $DIR/${des}

echo "************************************************************"

Id=98
#21641 -1% dp scan
keyrun=20827    
$PROG -pv -d DpVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Dp._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root 
        
#cat  $DIR/Sieve._20827_p4.f51 > $DIR/${des}

echo "************************************************************"

Id=196
#21627 0% dp scan
keyrun=20825    
$PROG -pv -d DpVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Dp._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root
        
echo "************************************************************"

Id=294
#21627 +1% dp scan
keyrun=21636    
$PROG -pv -d DpVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Dp._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root

        

cat $DIR/Dp._21642_p4.f51 $DIR/Dp._21641_p4.f51 $DIR/Dp._21627_p4.f51 $DIR/Dp._21636_p4.f51 > $DIR/${des}

echo "Done!"
