#!/bin/bash

## changed for PRex Optimization
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    echo "./myTree2AscII [path contains the cut files]  "
    echo "example: ./myTree2AscII ../Result "
    exit
fi

ARCH=$(arch)
PROG=./tree2ascii

ROOTFILEDIR="/home/newdriver/Storage/Research/PRex_Experiment/PRex_Replay/replay/Result/"

prefix="prexRHRS"
# Path that contains the cut 
DIR=$1
nfoil=1

des="Sieve.Full.test"

#IdOffSet=49
if [ -f $DIR/${des} ]
then
  mv -f $DIR/${des}  $DIR/${des}.old
fi



Id=0
# run 21646, -2% dp scan

keyrun=20826
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_2.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_3.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_4.root
        
Id=98
#21641 -1% dp scan
keyrun=20827    
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_2.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_3.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_4.root 
        #\
        #$ROOTFILEDIR/prexRHRS_20827_-1_2.root \
        #$ROOTFILEDIR/prexRHRS_20827_-1_3.root 

Id=196
#21636 0% dp scan
keyrun=20825    
$PROG -pv -d SieveVars.def -O $Id\
        -s $DIR/prexRHRS_${keyrun}.SieveCut.ncut \
        -c $DIR/prexRHRS_${keyrun}.SieveCut.cut \
        -g $DIR/prexRHRS_${keyrun}_-1.root.FullCut.root \
        -o $DIR/Sieve._${keyrun}_p4.f51 \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_1.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_2.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_3.root \
        $ROOTFILEDIR/prexRHRS_${keyrun}_-1_4.root  
     




cat $DIR/Sieve._20826_p4.f51  $DIR/Sieve._20827_p4.f51 $DIR/Sieve._20825_p4.f51 > $DIR/${des}

echo "Done!"
